services:
  backend:
    build: "./backend"
    image: "user-management-backend"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb+srv://abhrajitdebnathcs_db_user:abhrajit20@cluster0.35vqa0a.mongodb.net/?appName=Cluster0
      - JWT_SECRET=secret123
    
  frontend:
    build: "./frontend"
    image: "user-management-frontend"
    ports:
      - "3000:3000"

