services:
  backend:
    build: "./backend"
    image: "user-management-backend"
    ports:
      - "8000:8000"
    environment:
      - ./backend/.env
    
  frontend:
    build: "./frontend"
    image: "user-management-frontend"
    ports:
      - "3000:3000"

